const types = {
    ALL_EMPRESAS_REQUEST: "ALL_EMPRESAS_REQUEST",
    ALL_EMPRESAS_SUCCESS: "ALL_EMPRESAS_SUCCESS",
    ALL_EMPRESAS_FAILURE: "ALL_EMPRESAS_FAILURE",

    FILTER_EMPRESAS_REQUEST: "FILTER_EMPRESAS_REQUEST",
    FILTER_EMPRESAS_SUCCESS: "FILTER_EMPRESAS_SUCCESS",

    ADD_EMPRESA_REQUEST: "ADD_EMPRESA_REQUEST",
    ADD_EMPRESA_SUCCESS: "ADD_EMPRESA_SUCCESS",
    ADD_EMPRESA_FAILURE: "ADD_EMPRESA_FAILURE",

    UPDATE_EMPRESA_REQUEST: "UPDATE_EMPRESA_REQUEST",
    UPDATE_EMPRESA_SUCCESS: "UPDATE_EMPRESA_SUCCESS",
    UPDATE_EMPRESA_FAILURE: "UPDATE_EMPRESA_FAILURE",

    DELETE_EMPRESA_REQUEST: "DELETE_EMPRESA_REQUEST",
    DELETE_EMPRESA_SUCCESS: "DELETE_EMPRESA_SUCCESS",
    DELETE_EMPRESA_FAILURE: "DELETE_EMPRESA_FAILURE",

    SET_EMPRESA: "SET_EMPRESA",           // controla form no drawer
    SET_COMPONENTS: "SET_COMPONENTS",
    SET_ALERTA: "SET_ALERTA",
  };

  export default types;