export const OrderServiceActionTypes = {
  INITIALIZE_SEARCH_REQUESTED: '[Order Service] Initialize search requested',
  INITIALIZE_SEARCH_SUCCEEDED: '[Order Service] Initialize search succeeded',
  INITIALIZE_SEARCH_FAILED: '[Order Service] Initialize search failed',
  SEARCH_REQUESTED: '[Order Service] Search requested',
  SEARCH_SUCCEEDED: '[Order Service] Search succeeded',
  SEARCH_FAILED: '[Order Service] Search failed',
  LOAD_EDITOR_REQUESTED: '[Order Service] Load editor requested',
  LOAD_EDITOR_SUCCEEDED: '[Order Service] Load editor succeeded',
  LOAD_EDITOR_FAILED: '[Order Service] Load editor failed',
  SAVE_REQUESTED: '[Order Service] Save requested',
  SAVE_SUCCEEDED: '[Order Service] Save succeeded',
  SAVE_FAILED: '[Order Service] Save failed',
  RESET_SAVE_RESULT: '[Order Service] Reset save result',
  LOAD_SUPPLY_EDITOR_REQUESTED: '[Order Service] Load supply editor requested',
  LOAD_SUPPLY_EDITOR_SUCCEEDED: '[Order Service] Load supply editor succeeded',
  LOAD_SUPPLY_EDITOR_FAILED: '[Order Service] Load supply editor failed',
  CLOSE_SUPPLY_EDITOR: '[Order Service] Close supply editor',
  SAVE_SUPPLY_REQUESTED: '[Order Service] Save supply requested',
  SAVE_SUPPLY_SUCCEEDED: '[Order Service] Save supply succeeded',
  SAVE_SUPPLY_FAILED: '[Order Service] Save supply failed',
  DELETE_SUPPLY_REQUESTED: '[Order Service] Delete supply requested',
  DELETE_SUPPLY_SUCCEEDED: '[Order Service] Delete supply succeeded',
  DELETE_SUPPLY_FAILED: '[Order Service] Delete supply failed',
  LOOKUP_REQUESTED: '[Order Service] Lookup requested',
  LOOKUP_SUCCEEDED: '[Order Service] Lookup succeeded',
  LOOKUP_FAILED: '[Order Service] Lookup failed',
  CLEAR_LOOKUP: '[Order Service] Clear lookup',
} as const;
