const types = {
  LOAD_MY_COMPANY_REQUEST: "@salao/LOAD_MY_COMPANY_REQUEST",
  LOAD_MY_COMPANY_SUCCESS: "@salao/LOAD_MY_COMPANY_SUCCESS",
  LOAD_MY_COMPANY_FAILURE: "@salao/LOAD_MY_COMPANY_FAILURE",

  UPDATE_MY_COMPANY_REQUEST: "@salao/UPDATE_MY_COMPANY_REQUEST",
  UPDATE_MY_COMPANY_SUCCESS: "@salao/UPDATE_MY_COMPANY_SUCCESS",
  UPDATE_MY_COMPANY_FAILURE: "@salao/UPDATE_MY_COMPANY_FAILURE",
};

export default types;