const types = {
  FILTER_AGENDAMENTOS: "@agendamento/FILTER_AGENDAMENTOS",
  UPDATE_AGENDAMENTO: "@agendamento/UPDATE_AGENDAMENTO",
  UPDATE_AGENDAMENTO_STATE: "@agendamento/UPDATE_AGENDAMENTO_STATE",
  CREATE_AGENDAMENTO_REQUEST: "@agendamento/CREATE_AGENDAMENTO_REQUEST",
  EDIT_AGENDAMENTO_REQUEST: "@agendamento/EDIT_AGENDAMENTO_REQUEST",
  DELETE_AGENDAMENTO_REQUEST: "@agendamento/DELETE_AGENDAMENTO_REQUEST",
  SET_ALERTA_AGENDAMENTO: "@agendamento/SET_ALERTA_AGENDAMENTO",

  ALL_SERVICOS_REQUEST: "@agendamento/ALL_SERVICOS_REQUEST",
  UPDATE_SERVICOS_AGENDAMENTO: "@agendamento/UPDATE_SERVICOS_AGENDAMENTO",

  ALL_CLIENTES_REQUEST: "@agendamento/ALL_CLIENTES_REQUEST",
  UPDATE_CLIENTES_AGENDAMENTO: "@agendamento/UPDATE_CLIENTES_AGENDAMENTO",
};

export default types;