const types = {
  FILTER_CLIENTE: "@cliente/FILTER_CLIENTE",
  UPDATE_CLIENTE: "@cliente/UPDATE_CLIENTE",
  ADD_CLIENTE: "@cliente/ADD_CLIENTE",
  GET_CLIENTE: "@cliente/GET_CLIENTE",
  UPDATE_CADASTRO: "@cliente/UPDATE_CADASTRO",
  UPDATE_FORM: "@cliente/UPDATE_FORM",
  FILTER_AGENDAMENTOS: "@cliente/FILTER_AGENDAMENTOS",
  UPDATE_AGENDAMENTOS: "@cliente/UPDATE_AGENDAMENTOS",
  RESET_CLIENTE: "@cliente/RESET_CLIENTE",
  UPDATE_AGENDAMENTO: "@cliente/UPDATE_AGENDAMENTO",
  RESET_AGENDAMENTO: "@cliente/RESET_AGENDAMENTO",
};

export default types;
